<a href="https://colab.research.google.com/github/bybbaa/CHM/blob/main/%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%BD%D0%B04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Завдання 1

In [4]:
import numpy as np

a = np.array([[1, 2], [4, -1]])
b = np.array([[2, -3], [-4, 1]])

c = np.dot(a, b) - np.dot(b, a)

print("Матриця C:")
print(c)

Матриця C:
[[ 4 -8]
 [12 -4]]


Завдання 2

In [5]:
import numpy as np

matrix = np.array([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])

result = np.dot(matrix, matrix)

print("Матриця піднесена до степеня 2:")
print(result)

Матриця піднесена до степеня 2:
[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


Завдання 3

In [6]:
import numpy as np

matrix1 = np.array([[5, 0, 2, 3], [4, 1, 5, 3], [3, 1, -1, 2]])

matrix2 = np.array([[6], [-2], [7], [4]])

result = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(result)

Добуток матриць:
[[56]
 [69]
 [17]]


Завдання 4

In [13]:
import numpy as np

matrix = np.array([[0, 2, 0], [3, 4, 5], [6, 7, 8]])
determinant = np.linalg.det(matrix)
print("Визначник матриці :", determinant)

Визначник матриці : 12.0


Завдання 5

In [14]:
import numpy as np

matrix = np.array([[1, 2, 0, 0, 0],
                   [1, 0, 2, 0, 0],
                   [1, 0, 0, 2, 0],
                   [1, 0, 0, 0, 2],
                   [0, 0, 1, 1, 1]])

determinant = np.linalg.det(matrix)

print("Визначник матриці:")
print(determinant)

Визначник матриці:
-23.999999999999993


Завдання 6

In [26]:
import numpy as np

matrix = np.array([[2, 5, 7],
                   [6, 3, 4],
                   [5, -2, -3]])

inverse_matrix = np.linalg.inv(matrix)

print("Обернена матриця:")
print(inverse_matrix)

Обернена матриця:
[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


Завдання 7

In [25]:
import numpy as np

matrix = np.array([[-2, 3, 1, -1],
                   [3, 2, 1, 4],
                   [1, 2, 3, 4],
                   [0, 2, 3, 3]])

rank = np.linalg.matrix_rank(matrix)

print("Ранг матриці:", rank)

Ранг матриці: 3


Завдання 8 (метод Крамера)

In [87]:
import numpy as np

a = np.matrix('1 -2 3; 4 2 -3; 3 -3 5')
b = np.matrix('-5; 0; -9')

def kram(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        a1 = np.matrix(a)
        a2 = np.matrix(a)
        a3 = np.matrix(a)
        a1[:, 0] = b
        a2[:, 1] = b
        a3[:, 2] = b
        x = np.linalg.det(a1) / det_a
        y = np.linalg.det(a2) / det_a
        z = np.linalg.det(a3) / det_a
        print('Вирішення системи лінійних алгебраїчних рівнянь методом Крамера')
        print('x =', x.round(3), 'y =', y.round(3), 'z =', z.round(3))
    else:
        print("Визначник дорівнює нулю, система не має розв'язків")
    return x, y, z

kram(a, b)

print('Перевірка правильності розв\'язку\n', np.linalg.solve(a, b).round(3))


Вирішення системи лінійних алгебраїчних рівнянь методом Крамера
x = -1.0 y = 2.0 z = 0.0
Перевірка правильності розв'язку
 [[-1.]
 [ 2.]
 [-0.]]


Завдання 8 (матричний метод)

In [77]:
import numpy as np

a = np.array([[1, -2, 3],
              [4, 2, -3],
              [3, -3, 5]])

b = np.array([[-5],
              [0],
              [-9]])

x = np.linalg.solve(a, b)

print('Розв\'язок системи лінійних рівнянь:')
print('x =', x[0, 0])
print('y =', x[1, 0])
print('z =', x[2, 0])

Розв'язок системи лінійних рівнянь:
x = -1.0
y = 2.0
z = -0.0


Перевірка

In [88]:
import numpy as np
from scipy.linalg import solve

A = np.array([[1, -2, 3],
              [4, 2, -3],
              [3, -3, 5]])

b = np.array([-5, 0, -9])

x = solve(A, b)

print("Розв'язок системи:")
print("x =", x[0])
print("y =", x[1])
print("z =", x[2])


Розв'язок системи:
x = -1.0
y = 2.0
z = -0.0


Завдання 2(3 варіант)

In [82]:
import numpy as np

N = 6
M = 3

matrix = np.random.rand(N, M)

print("Нова матриця:")
print(matrix)

serednie_po_rjadku = np.mean(matrix, axis=1)
serednie_po_stovpcju = np.mean(matrix, axis=0)

print("\nСередні значення по рядках:")
print(serednie_po_rjadku)
print("\nСередні значення по стовпцях:")
print(serednie_po_stovpcju)

Нова матриця:
[[ 0.37145181  0.04257757  0.56712994]
 [ 0.09537581  0.56745439  0.24832205]
 [ 0.65028333  0.01741383  0.40019268]
 [ 0.64868899  0.89108349  0.86609865]
 [ 0.5900375   0.98758092  0.11929379]
 [ 0.33814162  0.04043652  0.7440958 ]]

Середні значення по рядках:
[ 0.32705311  0.30371742  0.35596328  0.80195704  0.56563741  0.37422465]

Середні значення по стовпцях:
[ 0.44899651  0.42442445  0.49085549]
